package main

import (
	"encoding/json"
	"fmt"

	nats "github.com/nats-io/go-nats"
)

type AutoGenerated struct {
	ID       string      `json:"id"`
	Pushed   int         `json:"pushed"`
	Device   string      `json:"device"`
	Created  int64       `json:"created"`
	Modified int         `json:"modified"`
	Origin   int64       `json:"origin"`
	Schedule interface{} `json:"schedule"`
	Event    interface{} `json:"event"`
	Readings []struct {
		ID       string `json:"id"`
		Pushed   int    `json:"pushed"`
		Created  int64  `json:"created"`
		Origin   int64  `json:"origin"`
		Modified int    `json:"modified"`
		Device   string `json:"device"`
		Name     string `json:"name"`
		Value    string `json:"value"`
	}
}

func main() {

	// Connect to a server
	var edgexReading = AutoGenerated{}
	fmt.Printf(nats.DefaultURL)
	nc, error := nats.Connect(nats.DefaultURL)
	if error != nil {
		fmt.Printf("Failed to connect")
	}
	defer closeConn(nc)
	// Simple Async Subscriber
	nc.Subscribe("out.unknown", func(m *nats.Msg) {
		fmt.Printf("Received a message: %s\n", string(m.Data))
		json.Unmarshal(m.Data, &edgexReading)
	})

}

func closeConn(nc *nats.Conn) {
	// Drain connection (Preferred for responders)
	// Close() not needed if this is called.
	nc.Drain()

	// Close connection
	nc.Close()
}
